### ISSUE TITLE
新版本 缺少参数 -b

### ISSUE THREAD

**Issue by openips** [gaoyifan/bgptools#1]
-b, --bgpdump-result <bgpdump-result> 

这个在新版本没了
china-operator-ip用不了

**Comment by openips** [comment]
0.0.3有 需要指定0.0.3安装才行

**Comment by gaoyifan** [comment]
0.1 采用了直接读取 MRT 的方式， 处理耗时会比先做 bgpdump 转换更短，但占用更多内存

bgptools-0.1 分支适配了这项改动，可以试试看
https://github.com/gaoyifan/china-operator-ip/tree/bgptools-0.1
https://github.com/gaoyifan/china-operator-ip/commit/ce1946dcd16584a6046df203272a73b2ee115b97

**Comment by openips** [comment]
试了一下bgptools-0.1 分支
内存占用过大
bgptools版本为0.1.1
VPS为Ubuntu 22.04 内存为12G
运行过程中报错bgptools 内存溢出

```
141425
xargs: bgptools: terminated by signal 9
INFO> generating IP list of cstnet ...
7497
17965
37944
xargs: bgptools: terminated by signal 9
INFO> generating IP list of drpeng ...
9395
```

可以优化的话最好优化一下
12G的内存对vps来说不小了

![image](https://user-images.githubusercontent.com/47168453/197318563-8a79e3bc-468e-4d76-a2f7-efffffa040a3.png)


最后很多IP列表都没有成功生成

```
 ./stat.sh
cernet
0

cernet6
672792581

china
0

china6
281474976710656

chinanet
0

chinanet6
268708319

cmcc
0

cmcc6
276569104

cstnet
0

cstnet6
1179648

drpeng
0

drpeng6
131072

googlecn
0

googlecn6
65568

tietong
0

tietong6
0

unicom
0

unicom6
33198352

```

**Comment by openips** [comment]
另外 0.0.3版本最后生成IP列表的时候会报错 但是IP结果是没问题的

报错日志如下：
```
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 8 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 12 but the index is 13', /home/song/.cargo/registry/src/github.com-1ecc6299db9ec823/bgptools-0.0.3/src/main.rs:32:32
no
```te: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


```

最终结果没有问题
```
./stat.sh
cernet
17181700

cernet6
672792581

china
302346085

china6
1662477947

chinanet
129214208

chinanet6
268708319

cmcc
37435136

cmcc6
276569104

cstnet
744960

cstnet6
1179648

drpeng
353024

drpeng6
131072

googlecn
8704

googlecn6
65568

tietong
20310272

tietong6
0

unicom
73436160

unicom6
33198352




```

**Comment by openips** [comment]
用回老版本解决问题
